export const skills = {
    JAVA: 'java',
    JAVA_EE: 'javaee',
    SPRING: 'spring',
    C_PLUS_PLUS: 'cplusplus',
    C_SHARP: 'csharp',
    MVC_NET: 'mvcnet',
    NET: 'net',
    ANGULAR: 'angular',
    PYTHON: 'python',
    ANDROID: 'android',
    XAMARIN: 'xamarin',
    HTML: 'html',
    CSS: 'css',
    JAVASCRIPT: 'javascript',
    TYPESCRIPT: 'typescript',
    KEYCLOAK: 'keycloak',
    MYSQL: 'mysql',
    MONGODB: 'mongodb',
    MAVEN: 'maven',
    GIT: 'git',
    LINUX: 'linux',
    DOCKER: 'docker'
};
